spring:
  rabbitmq:
    host: 192.168.61.14
    virtualHost: /
    username: guest
    password: guest
    
  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 2
    url: jdbc:postgresql://192.168.61.15:5432/trexzadb
    username: trexzadb
    password: trexza

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.61.100:8761/eureka/
