spring:
  rabbitmq:
    host: 10.1.100.15
    virtualHost: /
    username: guest
    password: guest
    
  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 2
    url: jdbc:postgresql://10.1.100.15:5432/trexzadb
    username: trexzadb
    password: trexza

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.10.101:8761/eureka/
  instance:
    hostname: ${host.name}
