spring:
  data:
    rest:
      basePath: /library
  jpa:
    show-sql: true
    hibernate:
      ddl-auto:

  jackson:
    serialization:
      INDENT_OUTPUT: true

audit:
  default:
    queue: audit.defaultQueue
    exchange: audit.defaultExchange
    routingKey: audit.defaultBinding

logging:
  level:
    org:
      springframework:
        data: DEBUG

javax:
  naming:
    Context:
      INITIAL_CONTEXT_FACTORY: org.apache.naming.java.javaURLContextFactory
