turbine:
  appConfig: micros
  clusterNameExpression: 'default'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

// **************** Rabbit MQ Properties ***********************
spring:
  rabbitmq:
    host: localhost
    virtualHost: /
    username: guest
    password: guest
