turbine:
  appConfig: micros, auditservice
  clusterNameExpression: 'default'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
      serviceUrl:
        defaultZone: http://10.1.10.101:8761/eureka/

spring:
  rabbitmq:
    host: 10.1.100.15
    virtualHost: /
    username: guest
    password: guest
