---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    //hostname: localhost1
    hostname: 10.1.10.101
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://10.1.10.101:8761/eureka/
      //defaultZone: http://localhost2:8762/eureka/   <<<<<<< switch to this one for using peer1 and peer2 in replicated setup
---      
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost1:8761/eureka/

      //defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
